### ISSUE TITLE
Illuminate\Translation\PotentiallyTranslatedString::__toString(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by aeusteixeira** [thefireflytech/filament-blog#15]
When I try to save any information in the bank I get this error. Can you help me?

![image](https://github.com/thefireflytech/filament-blog/assets/40412362/9d47e260-bd0c-46c8-af69-01db5e7a7b00)

**Comment by AsmitNepali** [comment]
@aeusteixeira Can you please give more details like, What are you trying to do and what are the steps that you face the issue?

**Comment by aeusteixeira** [comment]
I did the blog installation normally, created the categories, tags and register the blog information on the setting page. But this happens when I try to register a post.

**Comment by classicAmitIn** [comment]
It's hard to point the exact source of this error, may be something with filament or some other dependency. Try `composer update` command and than try to recreate the post.

**Comment by jringeisen** [comment]
Composer update doesn't fix it. I have this same issue. Fresh Laravel 11 install using Breeze with the Inertia Vue option. After installing Laravel I installed your package. First error I ran into was with the migrations, the migrations needed to be re-ordered in order to run successfully. But now I'm running into this error when trying to create a post.

**Comment by AsmitNepali** [comment]
@jringeisen @dimaswi  @aeusteixeira 

This issue is solved in our new update please update the package and follow these steps.

- `composer update`
-  remove existing blog migration from 
- `php artisan migrate`

Thank You.
